### ISSUE TITLE
Fix build error on ubuntu 20.04

### ISSUE THREAD

**Issue by markdumay** [markdumay/restic-unattended#24]
The generated docker-compose file has an invalid CPU value, crashing the build runner on GitHub. Below YML is an extract.
```yml
    deploy:
      resources:
        limits:
          cpus: '^A'
          memory: 100M
        reservations:
          cpus: '0.05'
          memory: 6M
```

The offending code is most likely caused by `generate_config()` in `dbm.sh`:
```
generate_config() {
    [ "${command}" = 'dev' ] && base_cmd="${DOCKER_RUN} ${docker_dev}" || 
        base_cmd="${DOCKER_RUN} ${docker_prod}"
    # fix incorrect CPU value (see https://github.com/docker/compose/issues/7771)
    cmd="${base_cmd} config | sed -E \"s/cpus: ([0-9\\.]+)/cpus: '\\1'/\""

    # replace tag if applicable
    if [ -n "${tag}" ]; then
        escaped_tag=$(escape_string "${tag}")
        cmd="${cmd} | sed -E 's|^    image: .*|    image: ${escaped_tag}|g'"
    fi

    echo "${cmd}"
}
```
